// <auto-generated />
using System;
using InternetSafetyPlan.Infrastructure.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternetSafetyPlan.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230913014359_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeviceTag", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeviceId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("DeviceTag");
                });

            modelBuilder.Entity("DeviceTeammate", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeammateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeviceId", "TeammateId");

                    b.HasIndex("TeammateId");

                    b.ToTable("DeviceTeammate");
                });

            modelBuilder.Entity("GoalDevice", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeviceId", "GoalId");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalDevice");
                });

            modelBuilder.Entity("GoalTag", b =>
                {
                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GoalId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("GoalTag");
                });

            modelBuilder.Entity("GoalTeammate", b =>
                {
                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeammateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GoalId", "TeammateId");

                    b.HasIndex("TeammateId");

                    b.ToTable("GoalTeammate");
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.DeviceAggregate.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.GoalAggregate.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("ActionItem");
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.GoalAggregate.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("UltimateGoalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UltimateGoalId");

                    b.ToTable("Goal");
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.Shared.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Type");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.TeamAggregate.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.TeamAggregate.Teammate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Teammate");
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.UltimateGoalAggregate.UltimateGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("UltimateGoal");
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DeviceTag", b =>
                {
                    b.HasOne("InternetSafetyPlan.Domain.DeviceAggregate.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_DeviceTag_Device_DeviceId");

                    b.HasOne("InternetSafetyPlan.Domain.Shared.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_DeviceTag_Tags_TagId");
                });

            modelBuilder.Entity("DeviceTeammate", b =>
                {
                    b.HasOne("InternetSafetyPlan.Domain.DeviceAggregate.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_DeviceTeammate_Device_DeviceId");

                    b.HasOne("InternetSafetyPlan.Domain.TeamAggregate.Teammate", null)
                        .WithMany()
                        .HasForeignKey("TeammateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_DeviceTeammate_Teammate_TeammateId");
                });

            modelBuilder.Entity("GoalDevice", b =>
                {
                    b.HasOne("InternetSafetyPlan.Domain.DeviceAggregate.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_GoalDevice_Device_DeviceId");

                    b.HasOne("InternetSafetyPlan.Domain.GoalAggregate.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_GoalDevice_Goal_GoalId");
                });

            modelBuilder.Entity("GoalTag", b =>
                {
                    b.HasOne("InternetSafetyPlan.Domain.GoalAggregate.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_GoalTag_Goal_GoalId");

                    b.HasOne("InternetSafetyPlan.Domain.Shared.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_GoalTag_Tags_TagId");
                });

            modelBuilder.Entity("GoalTeammate", b =>
                {
                    b.HasOne("InternetSafetyPlan.Domain.GoalAggregate.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_GoalTeammate_Goal_GoalId");

                    b.HasOne("InternetSafetyPlan.Domain.TeamAggregate.Teammate", null)
                        .WithMany()
                        .HasForeignKey("TeammateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_GoalTeammate_Teammates_TeammateId");
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.DeviceAggregate.Device", b =>
                {
                    b.HasOne("InternetSafetyPlan.Domain.TeamAggregate.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("InternetSafetyPlan.Domain.Shared.ManufacturerName", "Name", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Name");

                            b1.HasKey("DeviceId");

                            b1.ToTable("Device");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.OwnsOne("InternetSafetyPlan.Domain.Shared.Nickname", "Nickname", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Nickname");

                            b1.HasKey("DeviceId");

                            b1.ToTable("Device");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Nickname")
                        .IsRequired();
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.GoalAggregate.ActionItem", b =>
                {
                    b.HasOne("InternetSafetyPlan.Domain.GoalAggregate.Goal", null)
                        .WithMany("ActionItems")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("InternetSafetyPlan.Domain.Shared.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("ActionItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Description");

                            b1.HasKey("ActionItemId");

                            b1.ToTable("ActionItem");

                            b1.WithOwner()
                                .HasForeignKey("ActionItemId");
                        });

                    b.OwnsOne("InternetSafetyPlan.Domain.Shared.DueDate", "DueDate", b1 =>
                        {
                            b1.Property<Guid>("ActionItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("DueDate");

                            b1.HasKey("ActionItemId");

                            b1.ToTable("ActionItem");

                            b1.WithOwner()
                                .HasForeignKey("ActionItemId");
                        });

                    b.OwnsOne("InternetSafetyPlan.Domain.GoalAggregate.ActionItemName", "Name", b1 =>
                        {
                            b1.Property<Guid>("ActionItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Name");

                            b1.HasKey("ActionItemId");

                            b1.ToTable("ActionItem");

                            b1.WithOwner()
                                .HasForeignKey("ActionItemId");
                        });

                    b.Navigation("Description");

                    b.Navigation("DueDate");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.GoalAggregate.Goal", b =>
                {
                    b.HasOne("InternetSafetyPlan.Domain.UltimateGoalAggregate.UltimateGoal", null)
                        .WithMany("Goals")
                        .HasForeignKey("UltimateGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("InternetSafetyPlan.Domain.Shared.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Description");

                            b1.HasKey("GoalId");

                            b1.ToTable("Goal");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.OwnsOne("InternetSafetyPlan.Domain.Shared.DueDate", "DueDate", b1 =>
                        {
                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("DueDate");

                            b1.HasKey("GoalId");

                            b1.ToTable("Goal");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.OwnsOne("InternetSafetyPlan.Domain.GoalAggregate.GoalName", "Name", b1 =>
                        {
                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Name");

                            b1.HasKey("GoalId");

                            b1.ToTable("Goal");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.Navigation("Description");

                    b.Navigation("DueDate");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.TeamAggregate.Team", b =>
                {
                    b.OwnsOne("InternetSafetyPlan.Domain.Shared.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Description");

                            b1.HasKey("TeamId");

                            b1.ToTable("Team");

                            b1.WithOwner()
                                .HasForeignKey("TeamId");
                        });

                    b.OwnsOne("InternetSafetyPlan.Domain.TeamAggregate.TeamName", "Name", b1 =>
                        {
                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Name");

                            b1.HasKey("TeamId");

                            b1.ToTable("Team");

                            b1.WithOwner()
                                .HasForeignKey("TeamId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.TeamAggregate.Teammate", b =>
                {
                    b.HasOne("InternetSafetyPlan.Domain.TeamAggregate.Team", null)
                        .WithMany("Teammates")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InternetSafetyPlan.Domain.UserAggregate.User", null)
                        .WithOne()
                        .HasForeignKey("InternetSafetyPlan.Domain.TeamAggregate.Teammate", "UserId");

                    b.OwnsOne("InternetSafetyPlan.Domain.Shared.DateOfBirth", "DateOfBirth", b1 =>
                        {
                            b1.Property<Guid>("TeammateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("DateOfBirth");

                            b1.HasKey("TeammateId");

                            b1.ToTable("Teammate");

                            b1.WithOwner()
                                .HasForeignKey("TeammateId");
                        });

                    b.OwnsOne("InternetSafetyPlan.Domain.TeamAggregate.TeammateName", "Name", b1 =>
                        {
                            b1.Property<Guid>("TeammateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Name");

                            b1.HasKey("TeammateId");

                            b1.ToTable("Teammate");

                            b1.WithOwner()
                                .HasForeignKey("TeammateId");
                        });

                    b.Navigation("DateOfBirth");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.UltimateGoalAggregate.UltimateGoal", b =>
                {
                    b.HasOne("InternetSafetyPlan.Domain.TeamAggregate.Team", null)
                        .WithMany("UltimateGoals")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("InternetSafetyPlan.Domain.Shared.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("UltimateGoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Description");

                            b1.HasKey("UltimateGoalId");

                            b1.ToTable("UltimateGoal");

                            b1.WithOwner()
                                .HasForeignKey("UltimateGoalId");
                        });

                    b.OwnsOne("InternetSafetyPlan.Domain.UltimateGoalAggregate.UltimateGoalName", "Name", b1 =>
                        {
                            b1.Property<Guid>("UltimateGoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Name");

                            b1.HasKey("UltimateGoalId");

                            b1.ToTable("UltimateGoal");

                            b1.WithOwner()
                                .HasForeignKey("UltimateGoalId");
                        });

                    b.Navigation("Description");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.UserAggregate.User", b =>
                {
                    b.HasOne("InternetSafetyPlan.Domain.TeamAggregate.Team", null)
                        .WithMany("Users")
                        .HasForeignKey("TeamId");

                    b.OwnsOne("InternetSafetyPlan.Domain.Shared.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("User");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.GoalAggregate.Goal", b =>
                {
                    b.Navigation("ActionItems");
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.TeamAggregate.Team", b =>
                {
                    b.Navigation("Teammates");

                    b.Navigation("UltimateGoals");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("InternetSafetyPlan.Domain.UltimateGoalAggregate.UltimateGoal", b =>
                {
                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
