global using InternetSafetyPlan.Domain.Shared;
global using InternetSafetyPlan.Domain.UserAggregate;
global using InternetSafetyPlan.Domain.TeamAggregate;
global using InternetSafetyPlan.Domain.DeviceAggregate;
global using Xunit;
global using InternetSafetyPlan.Domain.Base;
global using InternetSafetyPlan.Domain.GoalAggregate;
global using InternetSafetyPlan.Domain.UltimateGoalAggregate;
global using MediatR;
